apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-crud-app
  template:
    metadata:
      labels:
        app: my-crud-app
    spec:
      containers:
        - name: my-crud-app
          image: bsle04/my-crud-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-crud-app-service
spec:
  type: NodePort
  selector:
    app: my-crud-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
