apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-crud-app
  template:
    metadata:
      labels:
        app: my-crud-app
    spec:
      containers:
        - name: my-crud-app
          image: bsle04/my-crud-app:latest
          ports:
            - containerPort: 3000
